### ISSUE TITLE
使用github是否对铺师不太友好？

### ISSUE THREAD

**Issue by cjyx9** [HanHan233/PhiCommunity-Charts-Repo#1]
话说，不是所有人会用git
整个上传站也好啊

**Comment by HanHan233** [comment]
他可以发issue找我加的，而且GitHub网页端也能直接上传文件夹来着，也不算难？

**Comment by HanHan233** [comment]
主要是，我没服务器，也没钱买服务器，服务器被D也完蛋（

**Comment by cjyx9** [comment]
啊哈哈，等我中考完了兴许有时间写一个挂在腾讯云的学生机上

**Comment by HanHan233** [comment]
还得是怕流量不够用，被D到黑洞那些的

**Comment by cjyx9** [comment]
腾讯云对学生有优惠，大厂也不怕d

**Comment by HanHan233** [comment]
我有个腾讯云lighthouse，但是我没备案

**Comment by cjyx9** [comment]
可以考虑爱发电拉点赞助？

**Comment by cjyx9** [comment]
备案简单，主要还是钱的问题

**Comment by HanHan233** [comment]
现在gh/cf pages是最便宜的方案了

**Comment by cjyx9** [comment]
但是你也知道github pages国内访问慢，几乎不能玩

**Comment by cjyx9** [comment]
cf好像有流量限制

**Comment by HanHan233** [comment]
流量没限制

**Comment by cjyx9** [comment]
要想做得像cy的社区，就必须踏出这一步

**Comment by HanHan233** [comment]
只是要是你的项目有函数那类的东西限制调用次数而已，我这个是纯静态的

**Comment by cjyx9** [comment]
目前开发阶段这样也行

**Comment by cjyx9** [comment]
还有，希望优化下手机ui，看着有丶难受

**Comment by HanHan233** [comment]
感觉比原来的好很多了（
